version: '3'
services:
  app:
    image: authentication
    build: .
    ports:
      - "3000:3000"
  nginx:
    image: nginx:stable
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"